version: 2

models:
  - name: dim_region
    columns:
      - name: region
        tests:
          - not_null
          - unique

  - name: dim_date
    columns:
      - name: month_start
        tests:
          - not_null
          - unique


  - name: dim_weather_bins
    columns:
      - name: bin_name
        tests: [not_null, unique]
      - name: t_min
      - name: t_max

  - name: fact_tourism_weather
    columns:
      - name: month_start
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: month_start

      - name: region
        tests:
          - not_null
          - relationships:
              to: ref('dim_region')
              field: region
